version: "3"
services:
  redis:
    image: redis
  mysql:
    image: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
      - "MYSQL_USER=${DB_USER_NAME}"
      - "MYSQL_PASSWORD=${DB_USER_PASSWORD}"
      - "MYSQL_DATABASE=fc_coupang"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
  web:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
  app:
    build:
      dockerfile: Dockerfile
    environment:
      - "PROFILE=develop"
      - "DB_USER_NAME=${DB_USER_NAME}"
      - "DB_USER_PASSWORD=${DB_USER_PASSWORD}"